<?php
return array(
       'seclevel'=>array('普通','绝密','机密','秘密'),
       'priority'=>array('普通','急件','紧急','特急'),
       'creDept'=>array('市委办公室','市委'),
       'commonSentence'=>array(
                            '有新的公文请您批示',
                            '有新的公文送达,请签收',
                            '请仔细阅读,认真把握该文件精神',
                            '请认真办理'
                    ),
       'modalVerb'=>array(
                '请',
                '责令'
        ),
       'action'=>array(
            '尽早办理'
        )
    );